/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteRouteImport } from './routes/panel/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelGitIndexRouteImport } from './routes/panel/git/index'
import { Route as PanelCollectionsIndexRouteImport } from './routes/panel/collections/index'
import { Route as PanelCollectionsCollectionIdRequestsIndexRouteImport } from './routes/panel/collections/$collectionId/requests/index'
import { Route as PanelCollectionsCollectionIdEnvironmentsIndexRouteImport } from './routes/panel/collections/$collectionId/environments/index'

const PanelRouteRoute = PanelRouteRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelGitIndexRoute = PanelGitIndexRouteImport.update({
  id: '/git/',
  path: '/git/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelCollectionsIndexRoute = PanelCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelCollectionsCollectionIdRequestsIndexRoute =
  PanelCollectionsCollectionIdRequestsIndexRouteImport.update({
    id: '/collections/$collectionId/requests/',
    path: '/collections/$collectionId/requests/',
    getParentRoute: () => PanelRouteRoute,
  } as any)
const PanelCollectionsCollectionIdEnvironmentsIndexRoute =
  PanelCollectionsCollectionIdEnvironmentsIndexRouteImport.update({
    id: '/collections/$collectionId/environments/',
    path: '/collections/$collectionId/environments/',
    getParentRoute: () => PanelRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteRouteWithChildren
  '/panel/collections/': typeof PanelCollectionsIndexRoute
  '/panel/git/': typeof PanelGitIndexRoute
  '/panel/collections/$collectionId/environments/': typeof PanelCollectionsCollectionIdEnvironmentsIndexRoute
  '/panel/collections/$collectionId/requests/': typeof PanelCollectionsCollectionIdRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteRouteWithChildren
  '/panel/collections': typeof PanelCollectionsIndexRoute
  '/panel/git': typeof PanelGitIndexRoute
  '/panel/collections/$collectionId/environments': typeof PanelCollectionsCollectionIdEnvironmentsIndexRoute
  '/panel/collections/$collectionId/requests': typeof PanelCollectionsCollectionIdRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteRouteWithChildren
  '/panel/collections/': typeof PanelCollectionsIndexRoute
  '/panel/git/': typeof PanelGitIndexRoute
  '/panel/collections/$collectionId/environments/': typeof PanelCollectionsCollectionIdEnvironmentsIndexRoute
  '/panel/collections/$collectionId/requests/': typeof PanelCollectionsCollectionIdRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/panel'
    | '/panel/collections/'
    | '/panel/git/'
    | '/panel/collections/$collectionId/environments/'
    | '/panel/collections/$collectionId/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/panel'
    | '/panel/collections'
    | '/panel/git'
    | '/panel/collections/$collectionId/environments'
    | '/panel/collections/$collectionId/requests'
  id:
    | '__root__'
    | '/'
    | '/panel'
    | '/panel/collections/'
    | '/panel/git/'
    | '/panel/collections/$collectionId/environments/'
    | '/panel/collections/$collectionId/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRouteRoute: typeof PanelRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/git/': {
      id: '/panel/git/'
      path: '/git'
      fullPath: '/panel/git/'
      preLoaderRoute: typeof PanelGitIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/collections/': {
      id: '/panel/collections/'
      path: '/collections'
      fullPath: '/panel/collections/'
      preLoaderRoute: typeof PanelCollectionsIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/collections/$collectionId/requests/': {
      id: '/panel/collections/$collectionId/requests/'
      path: '/collections/$collectionId/requests'
      fullPath: '/panel/collections/$collectionId/requests/'
      preLoaderRoute: typeof PanelCollectionsCollectionIdRequestsIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/collections/$collectionId/environments/': {
      id: '/panel/collections/$collectionId/environments/'
      path: '/collections/$collectionId/environments'
      fullPath: '/panel/collections/$collectionId/environments/'
      preLoaderRoute: typeof PanelCollectionsCollectionIdEnvironmentsIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
  }
}

interface PanelRouteRouteChildren {
  PanelCollectionsIndexRoute: typeof PanelCollectionsIndexRoute
  PanelGitIndexRoute: typeof PanelGitIndexRoute
  PanelCollectionsCollectionIdEnvironmentsIndexRoute: typeof PanelCollectionsCollectionIdEnvironmentsIndexRoute
  PanelCollectionsCollectionIdRequestsIndexRoute: typeof PanelCollectionsCollectionIdRequestsIndexRoute
}

const PanelRouteRouteChildren: PanelRouteRouteChildren = {
  PanelCollectionsIndexRoute: PanelCollectionsIndexRoute,
  PanelGitIndexRoute: PanelGitIndexRoute,
  PanelCollectionsCollectionIdEnvironmentsIndexRoute:
    PanelCollectionsCollectionIdEnvironmentsIndexRoute,
  PanelCollectionsCollectionIdRequestsIndexRoute:
    PanelCollectionsCollectionIdRequestsIndexRoute,
}

const PanelRouteRouteWithChildren = PanelRouteRoute._addFileChildren(
  PanelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRouteRoute: PanelRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
